### ISSUE TITLE
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

### ISSUE THREAD

**Issue by staylorx** [carlos-jenkins/plantweb#10]
I have a plantuml server behind TLS which I know is tested and strong, and publicly signed (though internal to my group). When I try to use it I get errors.

This might be you, it might be sphinx-doc? python2.7?

[I redacted mydomain. :)]
```
plantweb_defaults = {
    'server': 'https://pcamweb01.mydomain/plantuml/'
}
```

```
WARNING: C:\work\ART\cam-docs-art-system\environments\PRD.rst:22: (ERROR/3) Traceback (most recent call last):
  File "c:\python27\lib\site-packages\plantweb\directive.py", line 140, in run
    engine=self._get_engine_name()
  File "c:\python27\lib\site-packages\plantweb\render.py", line 199, in render
    output, sha = render_cached(server, format, content, **cacheopts)
  File "c:\python27\lib\site-packages\plantweb\render.py", line 122, in render_cached
    output = plantuml(server, format, content)
  File "c:\python27\lib\site-packages\plantweb\plantuml.py", line 123, in plantuml
    response = get(url)
  File "c:\python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "c:\python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```

Thank you!

**Comment by staylorx** [comment]
I tried changing the get in plantuml.py to 
```
response = get(url, verify=False)
```

But eventually it looks like it might just not have had all of it's defaults?

```
plantweb_defaults = {
#    'server': 'http://www.plantuml.com/plantuml/',    #<= this worked just fine btw
    "engine": 'plantuml',
    "format": 'svg',
    'server': 'https://pcamweb01.mydomain/plantuml/'
}
```

So far it appears that it might be working -- or it's cached! I'll update or close it if I find something.

**Comment by staylorx** [comment]
I had to ensure 'pip install requests[security]' was installed and turning off the cache seemed to ensure it would call. It complains about https but it gets it.

```
# Plantweb configuration
plantweb_defaults = {
#    'server': 'http://www.plantuml.com/plantuml/',
    'engine': 'plantuml',
    'format': 'svg',
    'server': 'https://pcamweb01.mydomain/plantuml/',
    'use_cache': False,
}
```

So it works locally now, but readthedocs in a Docker container seems to hate it. Something new for me to dig into. But your kit looks okay now.

Thanks much.

**Comment by staylorx** [comment]
Got far down the road then realized my _local_ copy of code had 

```
response = get(url, verify=False)
``` 

I started down the road of updating a fork, but got stuck a bit on the args.py. Creating a parameter called 'tlsverify' makes sense... does it need to be in the CLI?

**Comment by staylorx** [comment]
I think the ability to quickly disable SSL validation is all I really need. I had looked into REQUESTS_CA_BUNDLE but also ran into situations with SAN and wildcard naming. We've got a lot of docker and nginx before it's passed to a VIP. It's handy to check it with validation=False before sending clients against the VIP with the full cert and chain. Hacky, clearly. Thanks for your help.
