### ISSUE TITLE
1.2.1: `plantweb` documentation is not sphinx 4.x ready?

### ISSUE THREAD

**Issue by kloczek** [carlos-jenkins/plantweb#21]
Looks like `plantweb` documentation is not sphinx 4.x ready
```console
[tkloczko@barrel plantweb-1.2.1]$ sphinx-build -b man -d plantweb docs .

Application error:
Cannot find source directory (/home/tkloczko/rpmbuild/BUILD/plantweb-1.2.1/docs)
[tkloczko@barrel plantweb-1.2.1]$ sphinx-build -b man -d plantweb doc .
Running Sphinx v4.1.2

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/plantweb-1.2.1/doc/conf.py", line 299, in setup
    app.add_stylesheet('styles/custom.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
The full traceback has been saved in /tmp/sphinx-err-flyvy_yg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
[tkloczko@barrel plantweb-1.2.1]$ cat /tmp/sphinx-err-flyvy_yg.log
# Sphinx version: 4.1.2
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 251, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/plantweb-1.2.1/doc/conf.py", line 299, in setup
    app.add_stylesheet('styles/custom.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```

**Comment by kloczek** [comment]
gentle ping ..
In mean time sphinx moved to version 5.x
